[package]
name = "algo"
version = "0.1.0"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
license = "BSD-3-Clause"
license-file = "LICENSE"
repository = "https://github.com/GrayJack/algo"
description = "A collection of algorithms in rust"


[dependencies]
rand = "0.5.4"
